DATA:
  name: "imagenet_lt"
  img_size: 64
  num_classes: 1000
MODEL:
  backbone: "stylegan2"
  g_cond_mtd: "cAdaIN"
  d_cond_mtd: "SPD"
  g_act_fn: "Auto"
  d_act_fn: "Auto"
  z_prior: "gaussian"
  z_dim: 512
  w_dim: 512
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
  apply_g_ema: True
  add_emb_noise: True
  effective_number_samples_beta: 0
  emb_noise_std: 0.25
LOSS:
  adv_loss: "logistic"
  apply_r1_reg: True
  r1_lambda: 0.2048
  r1_place: "outside_loop"
  apply_noisytwins: True
  noisytwins_lambda: 0.001
  noisytwins_momentum_lambda: 0.005
  noisytwins_start_iter: 60000
OPTIMIZATION:
  # These values will be slightly changed if lazy regularization is applied.
  batch_size: 128
  acml_steps: 1
  g_lr: 0.0025
  d_lr: 0.0025
  beta1: 0
  beta2: 0.99
  d_first: False
  g_updates_per_step: 1
  d_updates_per_step: 1
  total_steps: 250000
AUG:
  apply_ada: True
  ada_aug_type: "bgc"
  ada_initial_augment_p: 0
  ada_target: 0.6
  ada_kimg: 500
  ada_interval: 4
STYLEGAN:
  g_reg_interval: 4
  d_reg_interval: 16
  mapping_network: 8
  style_mixing_p: 0.9
  g_ema_kimg: 20
  g_ema_rampup: "N/A"
  apply_pl_reg: True
  pl_weight: 2
  pl_start_iter: 60000
  d_architecture: "resnet"
  d_epilogue_mbstd_group_size: 8